<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <!--span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span-->
	<?php /** footer bottom links */ ?>
	<ul>
      <li><a href="#"><?php echo __('Returns and Refund Policy')?></a></li>
      <li><a href="#"><?php echo __('Shipping Policy')?></a></li>
      <li><a href="#"><?php echo __('Trademarks')?></a></li>
      <li><a href="#"><?php echo __('Website Terms & Conditions')?></a></li>
	  <li><a href="#"><?php echo __('Sales Terms & Conditions')?></a></li>
      <li><a href="#"><?php echo __('Legal Notices')?></a></li>
      <li><a href="#"><?php echo __('Privacy Policy')?></a></li>
  </ul>
</small>


