<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <!--span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span-->
	<?php /** footer bottom links */ ?>
	<ul>
      <li><a href="#">Returns and Refund Policy</a></li>
      <li><a href="#">Shipping Policy</a></li>
      <li><a href="#">Trademarks</a></li>
      <li><a href="#">Website Terms & Conditions</a></li>
	  <li><a href="#">Sales Terms & Conditions</a></li>
      <li><a href="#">Legal Notices</a></li>
      <li><a href="#">Privacy Policy</a></li>
  </ul>
</small>


