<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeManager->getStore()->getBaseUrl();
?>
<ul class="footer links">
    <li class="nav item">
    <h4><?php echo __('Industries') ?></h4>
    </li>
    <li class="nav item"><a href="<?php echo $storeManager->getStore()->getUrl()?>"><?php echo __('Education') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('First Responders') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('Government') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('Healthcare') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('Safety') ?></a></li>
</ul>
<ul class="footer links">
    <li class="nav item">
    <h4><?php echo __('Customer Support') ?></h4>
    </li>
    <li class="nav item"><a href="<?php echo $storeManager->getStore()->getUrl('contact')?>"><?php echo __('Contact Us') ?></a></li>
    <li class="nav item"><a href="<?php echo $storeManager->getStore()->getUrl('sales/guest/form')?>"><?php echo __('Returns') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('Getting Around fishersci.com') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('eProcurement Integration Solutions') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('Quality Systems') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('Mobile Apps') ?></a></li>
</ul>
<ul class="footer links">
    <li class="nav item">
        <h4><?php echo __('Services') ?></h4>
    </li>
    <li class="nav item"><a href="#"><?php echo __('Fisher Scientific Safety Services') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('Thermo Fisher Financial Services') ?></a></li>
    <li class="nav item"><a href="#"><?php echo __('Encompass Procurement Services') ?></a></li>
</ul>