<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();


?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
	<?php
		$om = \Magento\Framework\App\ObjectManager::getInstance();
		$context = $om->get('Magento\Framework\App\Http\Context');
		$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
		if($isLoggedIn){ ?>

		<li class="greet welcome" data-bind="scope: 'customer'">
            <span data-bind="text: customer().fullname ? $t('Welcome, %1!').replace('%1', customer().fullname) : '<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script> 
		
		<?php } ?>
        
    <?php  break; ?> 

    <?php case 'other': ?>
        <?php echo $block->getChildHtml(); ?>
    <?php break; ?>

<?php endswitch; ?>

<script type="text/javascript">
 $(document).ready(function() {
     if(jQuery(window).width() < 767){
			$(".greet.welcome").click(function(event) {
			    $(".customer-menu").css("display","block");
				event.stopPropagation();
			});				
			$(document).click(function(event) {
				$(".customer-menu").css("display","none");
			});
				
	 }else{
	  $(".customer-menu").css("display","block");
	 }
 });
 $(window).resize(function(){
		if(jQuery(window).width() < 767){
			$(".customer-menu").css("display","none");
			$(".greet.welcome").click(function(event) {
				$(".customer-menu").css("display","block");
				event.stopPropagation();
			});				
			$(document).click(function(event) {
				$(".customer-menu").css("display","none");
			});
		}else{
		 $(".customer-menu").css("display","block");
		}
});
</script>
