<div class="dropdown">
<button class="dropbtn">Shop Products</button>
<nav id="main-nav" role="navigation" class="main-nav">
	<ul id="main-menu" class="sm sm-vertical sm-blue">
		<?php echo $this->getHtml() ?>
	</ul>
</nav>
</div>

<script type="text/javascript">
  // <![CDATA[ 
	require(['jquery','js/jquery.smartmenus'], function($,smartmenus){
		 $.noConflict();
          $(window).load(function(){
                 $('#main-menu').smartmenus({
					mainMenuSubOffsetX: 1,
					mainMenuSubOffsetY: -8,
					subMenusSubOffsetX: 1,
					subMenusSubOffsetY: -8
				});
           });
	});
	// ]]> 
		
	$(document).ready(function(){		
		if (jQuery('body').is('.cms-home') && jQuery(window).width() >=768) {
			jQuery(".main-nav").css("display","block");
		}
		
		$(window).resize(function(){
			if (jQuery('body').is('.cms-home') && jQuery(window).width() >=768) {
				jQuery(".main-nav").css("display","block");		
			}else{
				jQuery(".main-nav").css("display","none");				
				$( ".dropdown" )
				  .mouseenter(function() {
					jQuery(".main-nav").css("display","block");
					if(jQuery(window).width() <=767){
						 jQuery(".block-search .label").css("display","none");
					}
				  })
				  .mouseleave(function() {
					if(jQuery(window).width() <=767){
						jQuery(".main-nav").css("display","none");
						jQuery(".block-search .label").css("display","block");
					}
				  });
			}
		});
		 $( ".dropdown" )
		  .mouseenter(function() {
			jQuery(".main-nav").css("display","block");
			if(jQuery(window).width() <=767){
						 jQuery(".block-search .label").css("display","none");
					}
		  })
		  .mouseleave(function() {
				if(jQuery(window).width() <=767 || !(jQuery('body').is('.cms-home'))){
							jQuery(".main-nav").css("display","none");
							jQuery(".block-search .label").css("display","block");
				}
				
		  });
	});	
</script>



